version: '3.8'

networks:
  zhfw-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  ZHFW-Eureka:
    image: easyz/zhfw-eureka:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.10
    ports:
      - "8761:8761"
    container_name: zhfw-eureka

  ZHFW-Bookstore:
    image: easyz/zhfw-bookstore:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.2
    ports:
      - "8082:8082"
    container_name: zhfw-bookstore
    depends_on:
      - ZHFW-Eureka

  ZHFW-Warehouse:
    image: easyz/zhfw-warehouse:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.3
    ports:
      - "8083:8083"
    container_name: zhfw-warehouse
    depends_on:
      - ZHFW-Eureka

  ZHFW-Payment:
    image: easyz/zhfw-payment:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.4
    ports:
      - "8084:8084"
    container_name: zhfw-payment
    depends_on:
      - ZHFW-Eureka

  ZHFW-HotelReservation:
    image: easyz/zhfw-hotelreservation:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.5
    ports:
      - "8085:8085"
    container_name: zhfw-hotelreservation
    depends_on:
      - ZHFW-Eureka

  ZHFW-FlightTicket:
    image: easyz/zhfw-flightticket:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.6
    ports:
      - "8086:8086"
    container_name: zhfw-flightticket
    depends_on:
      - ZHFW-Eureka

  ZHFW-Weather:
    image: easyz/zhfw-weather:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.7
    ports:
      - "8087:8087"
    container_name: zhfw-weather
    depends_on:
      - ZHFW-Eureka

  ZHFW-ServiceRetrieval:
    image: easyz/zhfw-serviceretrieval:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.8
    ports:
      - "8088:8088"
    container_name: zhfw-serviceretrieval
    depends_on:
      - ZHFW-Eureka

  ZHFW-TravelAgency:
    image: easyz/zhfw-travelagency:latest
    networks:
      zhfw-network:
        ipv4_address: 172.28.0.9
    ports:
      - "8089:8089"
    container_name: zhfw-travelagency
    depends_on:
      - ZHFW-Eureka
